INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NME', '116', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NME10', '116', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NMF', '116', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NMF10', '116', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE10', '115', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP10', '115', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE12', '118', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP12', '118', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTF12', '203', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP10', '303', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE10', '403', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE12', '404', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);

INSERT INTO ASSESSMENT_REQUIREMENT (ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP12', '304', 'API_ASSESSMENT', SYSDATE, 'JOCOX', SYSDATE);