UPDATE GRADUATION_PROGRAM_CODE
SET EFFECTIVE_DATE=TO_TIMESTAMP('1993-07-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3'), UPDATE_USER='API_GRAD_PROGRAM', UPDATE_DATE=SYSTIMESTAMP
WHERE GRADUATION_PROGRAM_CODE='SCCP';