ALTER TABLE GRADUATION_PROGRAM_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE GRADUATION_PROGRAM_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE CAREER_PROGRAM_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE CAREER_PROGRAM_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM_RQMT_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM_RQMT_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM_REQUIREMENT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE OPTIONAL_PROGRAM_REQUIREMENT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_REQUIREMENT_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_REQUIREMENT_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_REQUIREMENT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_REQUIREMENT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE REQUIREMENT_TYPE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE REQUIREMENT_TYPE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);