CREATE TABLE "PROGRAM_ASSESSMENT_REQUIREMENT"
(	"PROGRAM_ASSESSMENT_REQUIREMENT_ID" RAW(16) DEFAULT SYS_GUID(),
     "ASSESSMENT_TYPE_CODE" VARCHAR2(7) NOT NULL ENABLE,
     "PROGRAM_REQUIREMENT_CODE" VARCHAR2(4) NOT NULL ENABLE,
     "CREATE_USER" VARCHAR2(100) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(100) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     CONSTRAINT "PROGRAM_ASSESSMENT_REQUIREMENT_PK" PRIMARY KEY ("PROGRAM_ASSESSMENT_REQUIREMENT_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "PRGM_ASSESS_RQMT_PRG_RQMT_FK" FOREIGN KEY ("PROGRAM_REQUIREMENT_CODE")
         REFERENCES "PROGRAM_REQUIREMENT_CODE" ("PROGRAM_REQUIREMENT_CODE") ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY;

CREATE TABLE "OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT"
(	"OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT_ID" RAW(16) DEFAULT SYS_GUID(),
     "ASSESSMENT_TYPE_CODE" VARCHAR2(7) NOT NULL ENABLE,
     "OPTIONAL_PROGRAM_RQMT_CODE" VARCHAR2(4) NOT NULL ENABLE,
     "CREATE_USER" VARCHAR2(100) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(100) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     CONSTRAINT "OPT_PROG_ASSESS_REQ_PK" PRIMARY KEY ("OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "OPT_PROG_ASSESS_RQMT_OPT_RQMT_FK" FOREIGN KEY ("OPTIONAL_PROGRAM_RQMT_CODE")
         REFERENCES "OPTIONAL_PROGRAM_RQMT_CODE" ("OPTIONAL_PROGRAM_RQMT_CODE") ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY;
