INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NME', '116', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NME10', '116', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NMF', '116', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'NMF10', '116', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE10', '115', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP10', '115', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE12', '118', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP12', '118', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP10', '303', USER, SYSDATE, USER, SYSDATE);

INSERT INTO PROGRAM_ASSESSMENT_REQUIREMENT (PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, PROGRAM_REQUIREMENT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTP12', '304', USER, SYSDATE, USER, SYSDATE);


INSERT INTO OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT (OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, OPTIONAL_PROGRAM_RQMT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTF12', '203', USER, SYSDATE, USER, SYSDATE);

INSERT INTO OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT (OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, OPTIONAL_PROGRAM_RQMT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE10', '403', USER, SYSDATE, USER, SYSDATE);

INSERT INTO OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT (OPTIONAL_PROGRAM_ASSESSMENT_REQUIREMENT_ID, ASSESSMENT_TYPE_CODE, OPTIONAL_PROGRAM_RQMT_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), 'LTE12', '404', USER, SYSDATE, USER, SYSDATE);
