-- ASSESSMENT_REQUIREMENT definition

CREATE TABLE "ASSESSMENT_REQUIREMENT" 
   (	"ASSESSMENT_REQUIREMENT_ID" RAW(16) DEFAULT SYS_GUID(), 
	"ASSESSMENT_TYPE_CODE" VARCHAR2(7) NOT NULL ENABLE,
	"PROGRAM_REQUIREMENT_CODE" VARCHAR2(4) NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(100) DEFAULT USER NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(100) DEFAULT USER NOT NULL ENABLE,
	"UPDATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
   CONSTRAINT "ASSESSMENT_REQUIREMENT_PK" PRIMARY KEY ("ASSESSMENT_REQUIREMENT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;